import { Montserrat, Rhodium_Libre } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });
const rhodiumLibre = Rhodium_Libre({ 
  weight: '400',
  subsets: ["latin"], 
  variable: '--font-rhodium-libre'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${rhodiumLibre.variable}`}>{children}</body>
    </html>
  );
}